---
site_name: ExaCheck - BGP Health Checker
repo_url: https://github.com/exacheck/exacheck
repo_name: exacheck/exacheck

theme:
  name: material
  favicon: assets/images/icons/favicon.ico
  logo: assets/images/icons/bgp.svg

  # Use system fonts
  font: false

  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light Mode

watch:
  - includes

plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - def_list
  - footnotes
  - pymdownx.details
  - tables
  - pymdownx.inlinehilite

  - toc:
      permalink: true

  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true

  - pymdownx.snippets:
      base_path:
        - includes
      check_paths: true
      url_download: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  analytics:
    provider: google
    property: G-LZT47G0118
